### ISSUE TITLE
Crash on entering level

### ISSUE THREAD

**Issue by ChromaPIE** [eutropius225/CoversEverywhere#1]
Crash report is here: https://hastebin.com/axaxihelej.less

The CR shows `java.lang.NoClassDefFoundError: ic2/api/energy/tile/IEnergyEmitter`, but I don't have IC2 in the crashing instance.

**Comment by eutro** [comment]
While the crash log link you sent seems to be empty, that should have been fixed by 0.3.1, assuming you are on 0.3.0 with that crash.

**Comment by ChromaPIE** [comment]
Sorry for the empty crash report, looks good on my end but something might be wrong.

The new one here should be fine: https://paste.ubuntu.com/p/yTpdsVSrcp/

and also I do have 0.3.1 installed.

**Comment by eutro** [comment]
Okay, thanks for the report.
